import type { Metadata } from "next";
import { Lato } from "next/font/google";
import { AntdRegistry } from '@ant-design/nextjs-registry';
import Providers from "@/core/providers";
import ProtectedRoute from "@/hooks/protectedRoute";
import "./globals.scss";

const inter = Lato({ subsets: ["latin"], weight: '400' });

export const metadata: Metadata = {
    title: "Beincom",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <Providers>
                    <AntdRegistry>
                        <ProtectedRoute>
                            {children}
                        </ProtectedRoute>
                    </AntdRegistry>
                </Providers>
            </body>
        </html>
    );
}
